todo_testing_app/config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources 'todos'
end

todo_testing_app/app/models/todo.rb
class Todo < ActiveRecord::Base
	validates :item, presence: true
end

todo_testing_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo_testing_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
	
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.completed = false
		if @todo.save
			redirect_to action: "index"
		else
			render :new
		end
	end

	def destroy
		todo = Todo.find(params[:id])
		todo.delete
		redirect_to todos_path
	end


	private

		def todo_params
			params.require(:todo).permit(:item)
		end
end

todo_testing_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_testing_app/app/helpers/todo_helper.rb
module TodoHelper
end

todo_testing_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoTestingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%= yield %>
	</div>
</div>

</body>
</html>

todo_testing_app/app/views/todos/index.html.erb
<div class="page-header">
	<h1>Todo App</h1>
</div>

<ul class="list-group">
	<% @todos.each do |todo| %>
		<li class="list-group-item">
			<%= todo.item %>
			<%= button_to "Delete", {:controller => :todos, :action => :destroy, :id => todo.id}, 
				{:method => :delete, class: "btn btn-danger btn-sm"} %>
		</li>
	<% end %>
</ul>

<span class="glyphicon glyphicon-th-list"></span>&nbsp;&nbsp;<%= link_to "Add new item", new_todo_path %>

todo_testing_app/app/views/todos/new.html.erb
<div class="page-header">
	<h1>Todo App</h1>
</div>

<%= form_for @todo, :html => {:class => "form-horizontal"}  do |f| %>
	<div class="form-group">
		<%= f.label :item,  class: "control-label" %>
		<%= f.text_field :item, class: "form-control" %>
	</div>

	<%= f.submit "Submit", class: "btn btn-default btn-primary"  %>
<% end %>